### ISSUE TITLE
Purpose 

### ISSUE THREAD

**Issue by swimIan** [cow77/cbpi_owfs_Temp#1]
I am confused on this. Please add some info about the purpose or use of the plugin beyond the you later the one wire sensor in cbpi3. Thanks.

**Comment by cow77** [comment]
This plugin uses owfs (by pyowfs). So it is usable with "i2 °C to 1-wire Bridges" like ds2482.
Gives a more stable and reliable 1wire environment. Makes it possible to have more 1wire devices on the same bus.
